import{a as w,S as q,i}from"./assets/vendor-CucEYOFD.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))s(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const c of o.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&s(c)}).observe(document,{childList:!0,subtree:!0});function a(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function s(e){if(e.ep)return;e.ep=!0;const o=a(e);fetch(e.href,o)}})();const B="56323164-caf467cf771b73df75e13f6ca",P="https://pixabay.com/api/";async function m(t,r=1){const a={key:B,q:t,image_type:"photo",orientation:"horizontal",safesearch:!0,page:r,per_page:15};return(await w.get(P,{params:a})).data}const h=document.querySelector(".gallery"),l=document.querySelector(".loader"),u=document.querySelector(".load-more-btn"),M=new q(".gallery a",{captionsData:"alt",captionDelay:250});function g(t){const r=t.map(({webformatURL:a,largeImageURL:s,tags:e,likes:o,views:c,comments:v,downloads:S})=>`
      <li class="gallery-item">
        <a class="gallery-link" href="${s}">
          <img class="gallery-image" src="${a}" alt="${e}" />
        </a>
        <div class="info">
          <p class="info-item"><b>Likes</b> <span class="info-value">${o}</span></p>
          <p class="info-item"><b>Views</b> <span class="info-value">${c}</span></p>
          <p class="info-item"><b>Comments</b> <span class="info-value">${v}</span></p>
          <p class="info-item"><b>Downloads</b> <span class="info-value">${S}</span></p>
        </div>
      </li>
    `).join("");h.insertAdjacentHTML("beforeend",r),M.refresh()}function R(){h.innerHTML=""}function y(){l&&l.classList.remove("is-hidden")}function b(){l&&l.classList.add("is-hidden")}function L(){u&&u.classList.remove("is-hidden")}function d(){u&&u.classList.add("is-hidden")}const $=document.querySelector(".form"),O=document.querySelector(".load-more-btn");let f="",n=1,p=0;$.addEventListener("submit",x);O.addEventListener("click",C);async function x(t){t.preventDefault();const r=t.currentTarget,a=r.elements["search-text"].value.trim();if(a===""){i.warning({title:"Warning",message:"Please enter a search query!",position:"topRight"});return}f=a,n=1,R(),d(),y();try{const s=await m(f,n);if(p=s.totalHits,s.hits.length===0){i.error({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"});return}g(s.hits),p>n*15?L():i.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"})}catch(s){console.error(s),i.error({message:"Something went wrong. Please try again later.",position:"topRight"})}finally{b(),r.reset()}}async function C(){n+=1,d(),y();try{const t=await m(f,n);g(t.hits),E(),p>n*15?L():(d(),i.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"}))}catch(t){console.error(t),i.error({message:"Failed to load more images.",position:"topRight"})}finally{b()}}function E(){const t=document.querySelector(".gallery-item");if(t){const{height:r}=t.getBoundingClientRect();window.scrollBy({top:r*2,behavior:"smooth"})}}
//# sourceMappingURL=index.js.map
